export interface MaterialverwendungEingabe {
  id: string,
  verpackungId: Number,
  materialId: Number,
  verarbeitungId: Number,
  recyclingverfahrenId: Number,
  energierueckgewinnungId: Number,
  transportmittelId: Number,
  energierueckgewinnung: string,
  material: string,
  verarbeitung: string,
  recyclingverfahren: string,
  transportmittel: string,
  menge: Number,
  flaeche: Number,
  dicke: Number,
  recyclingQuote: Number,
  transportstrecke: Number,
}