export interface Materialverwendung {
  layer: number,
  materialId: string,
  verarbeitungId: string,
  recyclingverfahrenId: string,
  energierueckgewinnungId: string,
  transportmittelId: string,
  menge: number,
  flaeche: number,
  dicke: number,
  recyclingQuote: number,
  transportstrecke: number,
  materialCO2Eq?: number,
  materialEnergie?: number,
  energieAufwandVerarbeitung?: number,
  verbrennungCo2Eq?: number,
  verbrennungENutzEnergie?: number,
  gutschriftVerbrennungCo2Eq?: number,
  transportCo2Eq?: number,
  transportEnergie?: number,
  indirectco2Biofuel?: number,
  co2AufwandVerarbeitung?: number,
  verbrennungBioCo2Eq?: number,
  herstellungBioCo2Eq?: number,
}