export interface MaterialverwendungEingabe {
  id: string,
  verpackungId: number,
  layer: number,
  materialId: number,
  verarbeitungId: number,
  recyclingverfahrenId: number,
  energierueckgewinnungId: number,
  transportmittelId: number,
  energierueckgewinnung: string,
  verarbeitung: string,
  recyclingverfahren: string,
  transportmittel: string,
  menge: number,
  flaeche: number,
  dicke: number,
  recyclingQuote: number,
  transportstrecke: number,
}