server {
    listen 0.0.0.0:80;
    listen [::]:80;
    default_type application/octet-stream;

    gzip                    on;
    gzip_comp_level         6;
    gzip_vary               on;
    gzip_min_length         1000;
    gzip_proxied            any;
    gzip_types              text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_buffers            16 8k;
    client_max_body_size    256M;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
server {
    listen 0.0.0.0:443 ssl;
    listen [::]:443 ssl;
    server_name         www.co2rechner.cloud;
    ssl_certificate     cert_co2rechner.cloud.crt;
    ssl_certificate_key co2rechner.key;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}